# Generated by Django 5.2.8 on 2026-04-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_dlc_nsqfelectronics_nsqfit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='certified_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='trained_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
