# Generated by Django 5.2.8 on 2026-04-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_alter_studentdata_certified_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='certified_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='trained_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
