# Generated by Django 6.0.1 on 2026-04-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_alter_dlc_id_alter_nsqfelectronics_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='course_name',
            field=models.CharField(blank=True, choices=[('Basic Computer Course (BCC)', 'Basic Computer Course (BCC)'), ('Course on Computer Concepts (CCC)', 'Course on Computer Concepts (CCC)'), ('CCC+ (Course on Computer Concepts Plus)', 'CCC+ (Course on Computer Concepts Plus)'), ('A-Level Course', 'A-Level Course'), ('O-Level Course', 'O-Level Course'), ('Other Short Term Course', 'Other Short Term Course')], max_length=100, null=True),
        ),
    ]
