# Generated by Django 6.0.1 on 2026-04-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_alter_studentdata_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='claimed',
            field=models.BooleanField(default=False),
        ),
    ]
